{{- if and (and .Values.ingress.enabled .Values.ingress.internet.enabled) (contains "eks" .Capabilities.KubeVersion.GitVersion) -}}
{{- $fullName := include "rest-service.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: internet-{{ .Release.Name }}
  labels:
    {{- include "rest-service.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.ingress.internet.tlsEnabled }}
    {{- if or .Values.ingress.internet.tlsOnly }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    {{- else }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP": 80}]'
    {{- end }}
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig":{"Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_302"}}'
    {{- end }}
    {{- with .Values.ingress.internet.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.healthCheck }}
    {{- if and .enabled .livenessPath }}
    prometheus.io/scrape-ylz: "true"         
    prometheus.io/path: {{ .livenessPath | quote }}
    {{- end }}
    {{- end }}
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/group.name: {{ .Values.ingress.internet.group }}
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - host: {{ .Values.ingress.internet.host | quote }}
      http:
        paths:
        {{- if and .Values.ingress.internet.tlsEnabled .Values.ingress.internet.httpToHttpsRedirectEnabled }}
        - pathType: ImplementationSpecific
          backend:
            service:
              name: ssl-redirect
              port:
                name: use-annotation
        {{- end }}
        - pathType: ImplementationSpecific
          backend:
            service:
                name: {{ .Release.Name }}
                port: 
                  number: {{ $svcPort }}
    {{- range .Values.ingress.internet.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
        {{- if and $.Values.ingress.internet.tlsEnabled $.Values.ingress.internet.httpToHttpsRedirectEnabled }}
          - pathType: ImplementationSpecific
            backend:
              service:
                name: ssl-redirect
                port:
                  name: use-annotation
          {{- end }}
          - pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $.Release.Name }}
                port: 
                  number: {{ $svcPort }}
    {{- end }}        
  {{- if .Values.ingress.internet.tlsEnabled }}
  tls:
    - hosts:
      - {{ .Values.ingress.internet.host | quote }}
      {{- range .Values.ingress.internet.hosts }}
      - {{ . | quote }}
      {{- end }}
  {{- end }}
{{- end }}
