{{- if .Values.envs.secret.enabled }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "rest-service.fullname" . }}-env-secret
data:
  {{- with .Values.envs.secret.data }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end}}


{{- if .Values.volumes.secret.enabled }}
{{- range $i,$volume := .Values.volumes.secret.configs }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rest-service.fullname" $ }}-vol{{ $i }}-secret
  labels:
    app.kubernetes.io/name: {{ include "rest-service.name" $ }}
    helm.sh/chart: {{ include "rest-service.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
data:
  {{- toYaml .data | nindent 2 }}
{{- end }}
{{- end }}

{{- $secret := lookup "v1" "Secret" .Release.Namespace "harbor-ylz" -}}
{{- if not $secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-ylz
  annotations:
    "helm.sh/resource-policy": keep
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3Iub3BzLnl1bmxpemhpLmNuIjp7ImF1dGgiOiJjSFZzYkY5dmJteDVPbkpRTURacVJqUlNabkF5VUVWdk4wRT0iLCJwYXNzd29yZCI6InJQMDZqRjRSZnAyUEVvN0EiLCJ1c2VybmFtZSI6InB1bGxfb25seSJ9fX0=
{{- end }}

{{- $secret := lookup "v1" "Secret" .Release.Namespace "acr-ylz" -}}
{{- if not $secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: acr-ylz
  annotations:
    "helm.sh/resource-policy": keep
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJwcm9kLW9wcy1yZWdpc3RyeS16amstMDEtcmVnaXN0cnktdnBjLmNuLXpoYW5namlha291LmNyLmFsaXl1bmNzLmNvbSI6eyJ1c2VybmFtZSI6InByb2Qtb3BzLXJlZ2lzdHJ5LXpqay0wMUAxODIwNjkxMDc3NzEyNDI1IiwicGFzc3dvcmQiOiIoa1d8R1h0N1d8RTZMOGdOd1ZJZTNnbVN3b2NFaXIhSyJ9fX0=
{{- end }}

{{- $secret := lookup "v1" "Secret" .Release.Namespace "acr-credential-ylz" -}}
{{- if not $secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: acr-credential-ylz
  annotations:
    "helm.sh/resource-policy": keep
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJhY3Iub3BzLnl1bmxpemhpLmNuIjp7InVzZXJuYW1lIjoicHJvZC1vcHMtcmVnaXN0cnktemprLTAxQDE4MjA2OTEwNzc3MTI0MjUiLCJwYXNzd29yZCI6IihrV3xHWHQ3V3xFNkw4Z053VkllM2dtU3dvY0VpciFLIn19fQ==
{{- end }}


#新增 qinlang acr
{{- $secret := lookup "v1" "Secret" .Release.Namespace "qinlang-acr" -}}
{{- if not $secret }}
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5jbi16aGFuZ2ppYWtvdS5hbGl5dW5jcy5jb20iOnsidXNlcm5hbWUiOiJnb29kb250aGUiLCJwYXNzd29yZCI6InFsMjI1MjUyOCIsImF1dGgiOiJaMjl2Wkc5dWRHaGxPbkZzTWpJMU1qVXlPQT09In19fQ==
kind: Secret
metadata:
  name: qinlang-acr
  annotations:
    "helm.sh/resource-policy": keep
type: kubernetes.io/dockerconfigjson
{{- end }}

