apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "rest-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
    {{- if .Values.jmx.enabled }}
    - port: {{ .Values.jmx.port }}
      targetPort: {{ .Values.jmx.port }}
      protocol: TCP
      name: jmx-http
    {{- end }}
    {{- range $i,$portInfo := .Values.service.extend }}
    {{- if  .isMetrics }}
    - name: {{ printf "y%v-%s" $i .name | trunc 15 | trimSuffix "-" }}
      port: {{ .port }}
      targetPort: {{ .port }}
      protocol: {{ default "TCP" .protocol }}
    {{- else }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .port }}
      protocol: {{ default "TCP" .protocol }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "rest-service.selectorLabels" . | nindent 4 }}
